### ISSUE TITLE
Repo to the API?

### ISSUE THREAD

**Issue by 0zul** [riimuru/AnimeLazer#1]
Just wondering where is the Repo to the API cuz I'd like to check it out.

**Comment by riimuru** [comment]
The API is still under development and will not be public until then.

**Comment by itspranavajay** [comment]
Oh

**Comment by 0zul** [comment]
@riimuru You have a Discord server or account that I can contact you with?

**Comment by riimuru** [comment]
@imlarx My discord: rem#1723

**Comment by riimuru** [comment]
Api repo: https://github.com/riimuru/gogoanime
